spring:
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd: --

ON_PREM_URL_ENV: prod
AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
