apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: historikk-topikk
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  acl:
    - team: teamfamilie
      application: familie-historikk #owner
      access: readwrite   # readwrite