name: Build & Deploy til Dev
on:
  pull_request_target:
    types: [ opened,synchronize,reopened,ready_for_review ]
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/navikt/familie-historikk:${{ github.sha }}
  VERSION: familie-historikk:${{ github.sha }}

jobs:
  build:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Bygg (dependabot)
        if: github.actor == 'dependabot[bot]'
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn verify --settings .m2/maven-settings.xml --file pom.xml
      - name: Bygg med maven + sonar
        if: github.actor != 'dependabot[bot]'
        env:
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify sonar:sonar --no-transfer-progress package --settings .m2/maven-settings.xml  -DtrimStackTrace=false --file pom.xml -Dchangelist= -Dsha1=-$TIMESTAMP-$(echo $GITHUB_SHA | cut -c1-7)
      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $IMAGE
  deploy:
    if: github.event.pull_request.draft == false
    name: Deploy to NAIS / GCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/nais/nais_dev_gcp.yaml,build_n_deploy/nais/topic.yaml
          VAR: VERSION=${{ env.VERSION }}
